# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: BadInternet@badinternet.me
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Github.thehangout.space
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.BadInterent.me" # the base hostname & protocol for your site
twitter_username: 
github_username:  pixel-studios

# Build settings
markdown: kramdown
